name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc nasm cmake xorriso mtools

    - name: Build kernel and ISO
      run: python3 build.py -build -f

    - name: Run artifact verification tests
      run: python3 build.py -test
